# VERSION 1.0.0 #
services:
  bucstop:
    image: ghcr.io/andersonjb1/bucstop-qwerty/webapp:latest
    container_name: bucstop
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
      - GIT_COMMIT_HASH=${GIT_COMMIT:-unknown}
    volumes:
      - snapshots-data:/app/Snapshots
      - logs-data:/app/Logs

  api-gateway:
    image: ghcr.io/andersonjb1/bucstop-qwerty/gateway:latest
    container_name: api-gateway
    ports:
      - "8081:80" # Expose API Gateway on localhost:8081
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}

  snake:
    image: ghcr.io/andersonjb1/bucstop-qwerty/snake:latest
    container_name: game-snake
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8082:80" # Expose Snake microservice on localhost:8082
    networks:
      - bucstop-network

  pong:
    image: ghcr.io/andersonjb1/bucstop-qwerty/pong:latest
    container_name: game-pong
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8083:80" # Expose Pong microservice on localhost:8083
    networks:
      - bucstop-network

  tetris:
    image: ghcr.io/andersonjb1/bucstop-qwerty/tetris:latest
    container_name: game-tetris
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8084:80" # Expose Tetris microservice on localhost:8084
    networks:
      - bucstop-network

  submission-gateway:
    # Uncomment the following next 3 lines once the code for the Submission Gateway is added.
    #build:
    #context: ./BucStop_SubmissionGateway/SubmissionGateway
    #dockerfile: Dockerfile
    # Using a placeholder "hello world" image since there isn't code to build yet.
    image: "hello-world" # This line should be deleted once Submission Gateway is implemented.
    container_name: submission-gateway
    ports:
      - "8085:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    volumes:
      - submission-data:/app/Submissions

  # Watchtower is an all in one CI/CD tool that allows us to periodically
  # check and see if our containers can be updated. If they can, it performs a
  # rolling update to the ones who need it.
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    ports:
      - "8086:80"
    networks:
      - bucstop-network
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # The following commands:
    # interval - the interval watchtower will check our container images
    # cleanup - removes the older images after the update
    # rolling-restart - updates one container at a time
    command: >
      --interval 30
      --cleanup
      --rolling-restart
    environment:
      - TZ=America/New_York # set your timezone (e.g. America/New_York)
      # --- Notifications ---
      #- WATCHTOWER_NOTIFICATIONS=shoutrrr
      #- WATCHTOWER_NOTIFICATION_URL=generic://default962441d550554349bad3baec43c3d7.41.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/04cd909fe116414ab6ef115b60d1ca5f/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=st--w13vrbVg1RZX56GOQ7qylatGcMJDBKdTIHFnNTY?template=json
      #- WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOGO=true   # optional, includes Watchtower logo in messages
      # --- Notification Levels ---
      #- WATCHTOWER_NOTIFICATIONS_LEVEL=info         # options: panic, fatal, error, warn, info, debug, trace

networks:
  bucstop-network:
    driver: bridge

volumes:
  snapshots-data:
    driver: local
  logs-data:
    driver: local
  submission-data:
    driver: local
