# VERSION 1.2.0 #
services:
  bucstop:
    image: ghcr.io/andersonjb1/bucstop-qwerty/webapp:latest
    container_name: bucstop
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
      - GIT_COMMIT_HASH=${GIT_COMMIT:-unknown}
    depends_on:
      - api-gateway
    volumes:
      - snapshots-data:/app/Snapshots
      - logs-data:/app/Logs

  api-gateway:
    image: ghcr.io/andersonjb1/bucstop-qwerty/gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8081:80" # Expose API Gateway on localhost:8081
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    depends_on:
      - snake
      - pong
      - tetris

  snake:
    image: ghcr.io/andersonjb1/bucstop-qwerty/snake:latest
    container_name: game-snake
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8082:80" # Expose Snake microservice on localhost:8082
    networks:
      - bucstop-network

  pong:
    image: ghcr.io/andersonjb1/bucstop-qwerty/pong:latest
    container_name: game-pong
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8083:80" # Expose Pong microservice on localhost:8083
    networks:
      - bucstop-network

  tetris:
    image: ghcr.io/andersonjb1/bucstop-qwerty/tetris:latest
    container_name: game-tetris
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8084:80" # Expose Tetris microservice on localhost:8084
    networks:
      - bucstop-network

  submission-gateway:
    # Uncomment the following next 3 lines once the code for the Submission Gateway is added.
    #build:
    #context: ./BucStop_SubmissionGateway/SubmissionGateway
    #dockerfile: Dockerfile
    # Using a placeholder "hello world" image since there isn't code to build yet.
    image: "hello-world" # This line should be deleted once Submission Gateway is implemented.
    container_name: submission-gateway
    #restart: unless-stopped
    ports:
      - "8085:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    volumes:
      - submission-data:/app/Submissions

networks:
  bucstop-network:
    driver: bridge

volumes:
  snapshots-data:
    driver: local
  logs-data:
    driver: local
  submission-data:
    driver: local
