name: Automated Selenium Testing

on:
  pull_request:
    branches:
      - main
      - Dev-1
      - Dev-2
      - Dev-3
      - Dev-4
      - Dev-5
      - Dev-6
      - Dev-7
      - Dev-8
      - Dev-9
      - Dev-10
      - Dev-11
      - Dev-12
      - Sprint-1
      - Sprint-2
      - Sprint-3
      - Sprint-4
      - Sprint-5
      - Sprint-6
      - Sprint-7
      - Sprint-8
      - Sprint-9
      - Sprint-10
      - Sprint-11
      - Sprint-12

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Start Containers
      run: |
         timeout 300s bash -c '
           env=containersLocal docker compose up -d
           echo "Waiting for containers to start..."
           docker compose wait || echo "docker compose wait timed out or failed"
         ' 
         sleep 5
         docker ps -a || true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Navigation Selenium Test
      run: |
        python ./.automatedTests/v1_0_1_NavigationTest.py

    - name: Run Play Base Games Selenium Test
      run: |
        python ./.automatedTests/v1_0_0_PlayBaseGamesTest.py

    - name: Shutdown Containers
      if: always()
      run: docker compose down
